package com.ridgid.oss.orm.jpa;

import com.ridgid.oss.orm.AutoGeneratedPrimaryKeyedEntity;
import com.ridgid.oss.orm.jpa.pk.IntIdPK;

/**
 * Example Usage:
 *
 * <pre>
 * {@code
 *      @Entity
 *      @Table(name="FooTable")
 *      @IdClass(IntIdPK.class)
 *      public class Foo implements AutoGeneratedIntIdPrimaryKeyedEntity {
 *          @Id
 *          @Column(name="Id")
 *          @GeneratedValue(strategy=GenerationType.SEQUENCE)
 *          private int id;
 *
 *          // .... other fields, etc
 *
 *          public Foo() {}
 *
 *          public Foo(IntIdPK pk) {
 *              this.id = pk.getId();
 *          }
 *
 *          @Override
 *          public IntIdPK getPk() { return new IntIdPK(id); }
 *
 *          @Override
 *          public int getId() { return id; }
 *
 *
 *          // .... other property/field getters/setters. etc
 *      }
 * }
 * </pre>
 */
@SuppressWarnings("unused")
public interface AutoGeneratedIntIdPrimaryKeyedEntity
        extends AutoGeneratedPrimaryKeyedEntity<IntIdPK> {
    int getId();
}
